export const DEFAULT_SIZE_OPTIONS = [
  { label: "4" },
  { label: "6" },
  { label: "8" },
  { label: "10" },
  { label: "12" },
  { label: "14" },
  { label: "16" },
  { label: "XS" },
  { label: "S" },
  { label: "M" },
  { label: "L" },
  { label: "XL" },
  { label: "2XL" },
  { label: "3XL" },
  { label: "4XL" },
  { label: "5XL" },
  { label: "6XL" },
] as const;
